version: 2.1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
jobs:
  build:
    docker:
      - image: cimg/node:12
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/<language>:<version TAG>
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: echo "this is the test job"
